<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_0 cancellation fee  Instant refund_chec_f55971</name>
   <tag></tag>
   <elementGuidId>6f5cf9e0-6ec1-426a-ab80-42a032d57589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.checkbox_wrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/div/div[3]/div[2]/div/form/div[4]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.checkbox_wrap</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>978c2287-21a1-4191-a7c9-4371e2bfa766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox_wrap</value>
      <webElementGuid>1a08ab04-54d3-44c9-808d-13d2659e0e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;banner-wrapper&quot;]/div[@class=&quot;banner&quot;]/div[@class=&quot;new_srp_widget_overlay&quot;]/div[@class=&quot;search-widget-wrapper&quot;]/div[@class=&quot;search-autosuggest-wrapper&quot;]/form[@class=&quot;search-widget&quot;]/div[@class=&quot;fc_optin_main_wrap_home&quot;]/div[@class=&quot;checkbox_wrap&quot;]</value>
      <webElementGuid>8b9adf5f-f77f-455e-9ad6-3a7c1357bab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/div/div[3]/div[2]/div/form/div[4]/div[2]</value>
      <webElementGuid>41ce055b-6b1a-44ae-ae3c-8067333f7da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>92fc4be9-78cd-4195-ad62-5ad01c1a6d0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
