<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_To</name>
   <tag></tag>
   <elementGuidId>17e39ee1-8fbe-4826-bb1a-53ce33e913ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-bdVaJa.fpFLOj > div.sc-ifAKCX.gLwVlD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='autoSuggestContainer']/div/div[3]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; To&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb542a9e-5e23-4c6e-9385-8accea281cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ifAKCX gLwVlD</value>
      <webElementGuid>ec4ac95b-b5a7-4cab-a2b4-48e7232e808a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>To</value>
      <webElementGuid>c2ded0a0-3126-4bb5-85e1-c6fb8f9d82d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoSuggestContainer&quot;)/div[@class=&quot;sc-ckVGcZ ikHMPa&quot;]/div[@class=&quot;sc-gqjmRU giWxzf&quot;]/div[@class=&quot;sc-VigVT ishpWr&quot;]/div[@class=&quot;sc-bdVaJa fpFLOj&quot;]/div[@class=&quot;sc-ifAKCX gLwVlD&quot;]</value>
      <webElementGuid>9a5068a0-8b96-4e5b-8dac-a38298fbbfb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='autoSuggestContainer']/div/div[3]/div/div/div</value>
      <webElementGuid>0f8604ff-f2ee-4ddf-9bcb-8e2b6d9a2fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Madurai'])[1]/following::div[6]</value>
      <webElementGuid>b2869a57-e28a-4ecb-a182-d9fe86d38019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periyar Bus Stand'])[1]/following::div[6]</value>
      <webElementGuid>743286b7-a5db-43ed-8448-1e94f87bcc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/preceding::div[3]</value>
      <webElementGuid>3892bb7a-69de-450f-86a1-e54b57259806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/div</value>
      <webElementGuid>10585975-1c71-42c6-8ec5-af955b365899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'To' or . = 'To')]</value>
      <webElementGuid>897337e7-062b-4df0-bd80-58cf52c5d50e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
