<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Madurai_sc-kpOJdX jVMfHp</name>
   <tag></tag>
   <elementGuidId>0305c16e-7dee-47a0-ad45-68fe4c39e04c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-kpOJdX.jVMfHp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='autoSuggestContainer']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.sc-kpOJdX</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>14718728-3a62-416b-976c-22b25cb4e481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-kpOJdX jVMfHp</value>
      <webElementGuid>0f463b73-d928-4d3e-b1f7-8d6123f42a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoSuggestContainer&quot;)/div[@class=&quot;sc-ckVGcZ ikHMPa&quot;]/div[@class=&quot;sc-kpOJdX jVMfHp&quot;]</value>
      <webElementGuid>eb1040da-fbfa-411f-bce2-0f831d770078</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='autoSuggestContainer']/div/div[2]</value>
      <webElementGuid>0aaa6cd3-8027-4a20-ad3d-7005bf2147de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Madurai'])[1]/following::div[2]</value>
      <webElementGuid>da05d36b-3c2a-46d5-8fb5-42dbfd52a9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periyar Bus Stand'])[1]/following::div[2]</value>
      <webElementGuid>2086d571-c381-4667-9cd4-2a85877b2c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/preceding::div[1]</value>
      <webElementGuid>4eae1b59-a679-46b7-8eba-018aca254f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Koyambedu'])[1]/preceding::div[1]</value>
      <webElementGuid>93214bcb-5539-4ee6-8c3c-53ad0b7504b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]</value>
      <webElementGuid>71fdee4f-e417-4851-8d30-c1c32737500f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
