<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_From_sc-jKJlTe fFQGdj icon-swaparrow</name>
   <tag></tag>
   <elementGuidId>af33983b-c94e-4cc8-8af9-50b321a5887f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.sc-jKJlTe.fFQGdj.icon-swaparrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='autoSuggestContainer']/div/div[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#autoSuggestContainer i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>aff595f0-c831-4740-9b4c-f3413192af92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-jKJlTe fFQGdj icon-swaparrow</value>
      <webElementGuid>aae14aac-bbf2-4a6f-a79b-d9445f25d90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoSuggestContainer&quot;)/div[@class=&quot;sc-ckVGcZ ikHMPa&quot;]/div[@class=&quot;sc-kpOJdX jVMfHp&quot;]/i[@class=&quot;sc-jKJlTe fFQGdj icon-swaparrow&quot;]</value>
      <webElementGuid>3bc3fdb1-12b7-41f8-8717-aeda6cbc49ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='autoSuggestContainer']/div/div[2]/i</value>
      <webElementGuid>1dacce89-f02e-497e-82ac-ecfd506cd419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/i</value>
      <webElementGuid>01bf99bf-f50b-4cf8-b1e5-9bcf52e4550e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
