<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Mattuthavani</name>
   <tag></tag>
   <elementGuidId>d6a33b08-759c-4c21-9e31-373da6ddfaca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='autoSuggestContainer']/div/div[3]/div/ul/li[2]/div/text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; To  Madurai  Mattuthavani Madurai  Periyar Bus Stand Madurai  Aruppukottai Bypass Madurai  Kalavasal Madurai  Fathima College Madurai  Arappalayam Madurai  Nagamalai Pudukkottai Madurai  Thiruparankundram Madurai  Ramnad Madurai  Guru Theatre Madurai  Kappalur Bypass Madurai  Sellur Madurai  Simakkal Madurai  Samyanallur Bypass Madurai  K K Nagar Madurai  Tiruvandram Madurai  Ellis Nagar Madurai  Madurairmtoffice Madurai  Thirumangalam Madurai  Paravai Madurai  Madurai Kovilpatti&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>848e39a6-868f-4795-a804-619dca200d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>placeHolderMainText</value>
      <webElementGuid>d40c5e68-3c3c-492a-bf36-08657a79cc03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mattuthavani</value>
      <webElementGuid>62a7386c-b042-4675-a7bf-57d4edbcbe5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoSuggestContainer&quot;)/div[@class=&quot;sc-ckVGcZ ikHMPa&quot;]/div[@class=&quot;sc-gqjmRU giWxzf&quot;]/div[@class=&quot;sc-VigVT ishpWr&quot;]/ul[@class=&quot;sc-dnqmqq eFEVtU&quot;]/li[@class=&quot;sc-iwsKbI jTMXri&quot;]/div[@class=&quot;sc-gZMcBi grvhsy&quot;]/text[@class=&quot;placeHolderMainText&quot;]</value>
      <webElementGuid>222b1390-5fa5-4911-bffa-005943ade3e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='autoSuggestContainer']/div/div[3]/div/ul/li[2]/div/text</value>
      <webElementGuid>cc649461-e44d-486e-9996-f2ff1758d06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Madurai'])[1]/following::text[1]</value>
      <webElementGuid>29f45384-365e-451b-be6a-f67cfa4b3079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/following::text[2]</value>
      <webElementGuid>2c0eeab0-6f90-4a3a-a518-43c5076564e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Madurai'])[2]/preceding::text[1]</value>
      <webElementGuid>9f32225e-7c3e-4b7c-a77c-3b0fbf6cd64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periyar Bus Stand'])[1]/preceding::text[2]</value>
      <webElementGuid>d27d3583-caeb-405a-a5f4-31e7eb900e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mattuthavani']/parent::*</value>
      <webElementGuid>3aeb16b4-ecef-43d8-b805-bf4384fbad26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/text</value>
      <webElementGuid>a7e3a37a-1be7-4905-b43a-e1dd9d3c7ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = 'Mattuthavani' or . = 'Mattuthavani')]</value>
      <webElementGuid>1d974a12-a6ed-4d8e-9584-70a6bf3f64a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
