<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Koyambedu</name>
   <tag></tag>
   <elementGuidId>d8f3592e-1839-406b-a986-10cf68317d11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='autoSuggestContainer']/div/div[3]/div/ul/li[4]/div/text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; To  Chennai  CMBT, Chennai Chennai  CMBT, Chennai Chennai  Koyambedu Chennai  Perungalathur Chennai  Vellore Bypass Chennai  Vandalur Chennai  Ashok Pillar Chennai  Alandur Chennai  Chrompet Chennai  Guindy Chennai  Sholinganallur Chennai  Porur Chennai  Pallavaram Chennai  Madhavaram Chennai  Mahabalipuram Chennai  Maduravoyal Chennai  Egmore Chennai  Velachery Chennai  Chennai Intl Airport&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3acdf222-3dcd-4dce-a215-5a82bc6e9da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>placeHolderMainText</value>
      <webElementGuid>e308ccaa-4d19-4c6a-94c8-a61227541a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Koyambedu</value>
      <webElementGuid>27f3ef55-653f-4846-a877-ed1c24c1dbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoSuggestContainer&quot;)/div[@class=&quot;sc-ckVGcZ ikHMPa&quot;]/div[@class=&quot;sc-gqjmRU giWxzf&quot;]/div[@class=&quot;sc-VigVT ishpWr&quot;]/ul[@class=&quot;sc-dnqmqq eFEVtU&quot;]/li[@class=&quot;sc-iwsKbI jTMXri&quot;]/div[@class=&quot;sc-gZMcBi grvhsy&quot;]/text[@class=&quot;placeHolderMainText&quot;]</value>
      <webElementGuid>b51de3eb-b055-4dbd-a1d2-2eecbfaa9f8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='autoSuggestContainer']/div/div[3]/div/ul/li[4]/div/text</value>
      <webElementGuid>8f2aa457-009e-4ed1-995c-e814f84635a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chennai'])[3]/following::text[1]</value>
      <webElementGuid>b0d77144-8f01-4a5a-bf0c-fcd2f0331718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CMBT, Chennai'])[2]/following::text[2]</value>
      <webElementGuid>6ceec55f-7bc4-4247-82fa-4fcf223ec179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chennai'])[4]/preceding::text[1]</value>
      <webElementGuid>4c9ea9ab-9b30-4955-9e31-5b04a7f461bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perungalathur'])[1]/preceding::text[2]</value>
      <webElementGuid>203029de-b479-4d5c-ac76-0e8319e58e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Koyambedu']/parent::*</value>
      <webElementGuid>1208ca4a-ed2d-4ba0-87b1-67dc734489d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/text</value>
      <webElementGuid>645f8e26-ac69-4fea-b036-4680541e854d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = 'Koyambedu' or . = 'Koyambedu')]</value>
      <webElementGuid>7d14bb50-0822-4c5f-991a-9b876bd0de9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
