<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_GSRTC</name>
   <tag></tag>
   <elementGuidId>e698faaa-02bb-43bb-bb42-7ced6337882a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/article[2]/div/div/ul[5]/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;GSRTC&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>32bf65a4-a4d7-4769-8e4b-063f2b5fde35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>D113_item_rtc</value>
      <webElementGuid>7d3dfcca-9cf4-43c2-a421-57ef8db902af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> GSRTC </value>
      <webElementGuid>1f395c7c-e11f-43b9-a6d8-6b2fa719507f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/article[2]/div[@class=&quot;D113_links_main&quot;]/div[@class=&quot;D113_ul_rtc&quot;]/ul[@class=&quot;D113_ul_region_rtc&quot;]/li[@class=&quot;D113_item_rtc&quot;]</value>
      <webElementGuid>a01d0316-e1fb-41b0-ac8b-8c41b0626380</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/article[2]/div/div/ul[5]/li[2]</value>
      <webElementGuid>c1d44802-ed45-4793-939c-75f6cf7f14f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='West'])[1]/following::li[1]</value>
      <webElementGuid>87185e0e-7f81-414a-a669-96cdffc2c7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENJOY THE APP!!'])[1]/preceding::li[1]</value>
      <webElementGuid>a1c8d83e-07a6-4775-8154-f33f0af7f6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[5]/li[2]</value>
      <webElementGuid>9ce86baa-c564-412b-9ebf-49137e8f16a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = ' GSRTC ' or . = ' GSRTC ')]</value>
      <webElementGuid>5eedd4fa-c072-40f5-8538-5d1a8e51616d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
