<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_East</name>
   <tag></tag>
   <elementGuidId>25a32ed2-24b3-40c6-9af7-888ef4f448f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/article[2]/div/div/ul[2]/li/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;East&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>163d46fa-081f-4ce5-b8fd-24e6c8728505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>East</value>
      <webElementGuid>cca06d82-194b-4628-9289-74c8c83d76bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/article[2]/div[@class=&quot;D113_links_main&quot;]/div[@class=&quot;D113_ul_rtc&quot;]/ul[@class=&quot;D113_ul_region_rtc&quot;]/li[1]/strong[1]</value>
      <webElementGuid>eaa5c46c-c7b6-4316-8b30-27de4a0763d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/article[2]/div/div/ul[2]/li/strong</value>
      <webElementGuid>433f8630-5d4e-48ee-b658-1b7d620f377c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='East']/parent::*</value>
      <webElementGuid>c9639b53-0487-422c-90b9-0e9c61ec468b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/strong</value>
      <webElementGuid>0fb7683b-16ed-4d03-a0ba-76bdf3fbfa77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'East' or . = 'East')]</value>
      <webElementGuid>5f28801c-65c4-43fe-a35c-cfa19abad35b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
