<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_NorthEast</name>
   <tag></tag>
   <elementGuidId>360b525b-d752-425b-99b6-bc424c35d667</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/article[2]/div/div/ul[4]/li/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;NorthEast&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>cbfe4e91-a090-433c-8453-396ab334c2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NorthEast</value>
      <webElementGuid>a8527e06-fd9c-4966-9cba-40e44244bbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/article[2]/div[@class=&quot;D113_links_main&quot;]/div[@class=&quot;D113_ul_rtc&quot;]/ul[@class=&quot;D113_ul_region_rtc&quot;]/li[1]/strong[1]</value>
      <webElementGuid>7558f242-9eec-4261-b51a-a830eb58178a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/article[2]/div/div/ul[4]/li/strong</value>
      <webElementGuid>77076e3b-3b69-49a9-800a-d80f7e6a9381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NorthEast']/parent::*</value>
      <webElementGuid>36f27057-8512-4f71-b8ef-75058205a11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[4]/li/strong</value>
      <webElementGuid>413e7cf4-f6db-4bfd-a810-aa42dfe6f388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'NorthEast' or . = 'NorthEast')]</value>
      <webElementGuid>1b503689-2699-47a5-8c71-4052931bfc35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
