<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_South</name>
   <tag></tag>
   <elementGuidId>504302ff-3fd3-4dae-acfa-11d60f82eafb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/article[2]/div/div/ul/li/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;South&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>40996a12-54d7-4449-92cc-6b8f686ca084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>South</value>
      <webElementGuid>415ec642-3e8b-4566-b25e-9473de5ff590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/article[2]/div[@class=&quot;D113_links_main&quot;]/div[@class=&quot;D113_ul_rtc&quot;]/ul[@class=&quot;D113_ul_region_rtc&quot;]/li[1]/strong[1]</value>
      <webElementGuid>21c46745-21c0-4f8d-a61c-7152c69e7b8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/article[2]/div/div/ul/li/strong</value>
      <webElementGuid>94a4e434-d902-4335-9f72-5792da2e21a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find All RTC Operator Directories'])[1]/following::strong[1]</value>
      <webElementGuid>3092efd7-b22e-44a6-a6e4-95ac986ea329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RTC Bus Directory'])[1]/following::strong[1]</value>
      <webElementGuid>80b95bec-4d12-43bd-8b38-9517ce451a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='South']/parent::*</value>
      <webElementGuid>e953860e-f8f6-44ff-a195-2a642256abde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>53749f25-4b26-4e39-8279-1a8a5562d6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'South' or . = 'South')]</value>
      <webElementGuid>2300b67e-eb9c-49a4-8c87-7dd7e60fd3fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
