<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_North</name>
   <tag></tag>
   <elementGuidId>de6b5109-497d-462c-b34f-bc6db2448bdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/article[2]/div/div/ul[3]/li/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;North&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>cfd32c43-6390-4e15-8e6b-f96870f0a372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>North</value>
      <webElementGuid>b5684693-4e0e-49a9-9c73-5a14465ac583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/article[2]/div[@class=&quot;D113_links_main&quot;]/div[@class=&quot;D113_ul_rtc&quot;]/ul[@class=&quot;D113_ul_region_rtc&quot;]/li[1]/strong[1]</value>
      <webElementGuid>d33fce25-ec35-4701-93a3-95b845d351ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/article[2]/div/div/ul[3]/li/strong</value>
      <webElementGuid>633e89b3-5b4f-4367-90dc-8e92a76a5a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='North']/parent::*</value>
      <webElementGuid>6f2f7ec8-da93-4946-b738-e69563169ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[3]/li/strong</value>
      <webElementGuid>fc9f0703-861b-4f13-8dc6-5322992b9178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'North' or . = 'North')]</value>
      <webElementGuid>6373c037-d4fd-40d9-9654-84caaef2e734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
