<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_12636  Vaigai Sf Express</name>
   <tag></tag>
   <elementGuidId>0bb2f585-59e7-4b36-b114-625612414537</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.lts_solr_wrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/section/div[2]/div[4]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;12636 | Vaigai Sf Express&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>72b1e6dc-590e-427f-9293-2e83a7ea5071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lts_solr_wrap</value>
      <webElementGuid>b23ab5fa-44f2-4138-acb6-f8a7a75eb5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12636  | Vaigai Sf Express</value>
      <webElementGuid>8c560ea6-1576-4e80-8370-4c1333d71053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;lts_dweb_main_wrap&quot;]/section[@class=&quot;banner-wrapper&quot;]/div[@class=&quot;banner&quot;]/div[@class=&quot;pnr-input-wrapper&quot;]/div[@class=&quot;lts_solr_wrap_main&quot;]/div[@class=&quot;lts_solr_wrap&quot;]</value>
      <webElementGuid>a2f11a1b-2fb4-4692-9fc8-7f6ddbb5d66e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/div[2]/div[4]/div/div</value>
      <webElementGuid>8ff90479-49a4-4904-908f-81ee5e776afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Status'])[1]/following::div[2]</value>
      <webElementGuid>0cf0da49-9174-45bc-80ea-1fd210dc6291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='|']/parent::*</value>
      <webElementGuid>4f7bac75-64ff-4046-a579-dea83f4da980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>29e9b0f3-16bc-42c3-8b3f-61dbeadc42da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '12636  | Vaigai Sf Express' or . = '12636  | Vaigai Sf Express')]</value>
      <webElementGuid>dc957c3e-c961-42ec-997a-844ac10378b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
