<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_12636  Vaigai Sf Express</name>
   <tag></tag>
   <elementGuidId>c974fd21-0cf6-4320-afcd-db472f2d86e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.lts_header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;12636 | Vaigai Sf Express&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0eca8f28-817d-4ecb-b76b-c490d2199ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lts_header</value>
      <webElementGuid>56bcb341-951b-4aa0-885f-ab921ccc2d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12636 | Vaigai Sf Express</value>
      <webElementGuid>26811a13-c31f-417c-8960-85f5d8281da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;lts_dweb_main_wrap&quot;]/div[@class=&quot;lts_desktop&quot;]/div[@class=&quot;lts_landing_page_main_wrap&quot;]/div[@class=&quot;lts_header_wrap&quot;]/div[1]/span[@class=&quot;lts_header&quot;]</value>
      <webElementGuid>be93e3e2-357a-461b-a9f7-c1abef5499cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/span</value>
      <webElementGuid>af1149c6-13d6-417e-800a-cdfdb939b170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel Ticket'])[1]/following::span[1]</value>
      <webElementGuid>b2f1f328-9fd5-4993-b3e3-60d60a66ef19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SignUp / Signin'])[1]/following::span[1]</value>
      <webElementGuid>4f4aa2c9-a368-4899-bb4f-69acd940f978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MADURAI JN'])[1]/preceding::span[1]</value>
      <webElementGuid>4590b2c6-284b-4e2a-9713-d80d12e01bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12636 | Vaigai Sf Express']/parent::*</value>
      <webElementGuid>bfe555a2-0709-4e32-83fe-bea882134aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span</value>
      <webElementGuid>58742ce2-64ca-4f52-84b6-b60487b6cb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '12636 | Vaigai Sf Express' or . = '12636 | Vaigai Sf Express')]</value>
      <webElementGuid>bfc9c2af-8e75-4768-9d97-83d316fdd66f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
