<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Onboarding</name>
   <tag></tag>
   <elementGuidId>6be30222-f304-4a4c-ada9-2356db4823f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.open_manage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='bs-navbar']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Onboarding &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>65dc957a-cc2c-44a1-8e74-2ebce2f3db21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ active: ((isActive('/Neighbourhood') || isActive('/AddNeighbourhood') || isActive('/Worksite') || isActive('/AddWorksite') || isActive('/AddHousing') || isActive('/Housing') || isActive('/Partner') || isActive('/Participant') || isActive('/Employer') || isActive('/AddEmployer') || isActive('/EmployerForm') || isActive('/Staff') || isActive('/AddStaff') || isActive('/Participant') || isActive('/AddParticipant') || isActive('/SelfFundedForm') || (loggedUserType === 'Partner' &amp;&amp; isActive('/Staff')) || ((loggedUserType === 'Partner' || loggedUserType === 'PartnerStaff') &amp;&amp; isActive('/AddStaff'))) &amp;&amp; OnboardingHeaderActive)}</value>
      <webElementGuid>fbdc8f3a-a24b-49c9-879d-9f9e64bb590e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>01bd6933-a4f6-46cc-afe8-913a56dd4f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>open_manage</value>
      <webElementGuid>6892da49-5fd7-400a-90ff-0fdab6b976d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Onboarding</value>
      <webElementGuid>36759046-b53c-42bf-bec2-720535a0bf72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/div[@class=&quot;sample ng-scope&quot;]/section[@class=&quot;bs-docs-nav navbar navbar-static-top nomargin manage_partner bb- ng-scope&quot;]/div[@class=&quot;container-fluid&quot;]/div[1]/nav[@id=&quot;bs-navbar&quot;]/ul[@class=&quot;nav navbar-nav navbar-left right_nav m-l-20 ng-scope&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;open_manage&quot;]</value>
      <webElementGuid>802b05e9-e489-45a2-8ced-45e82f47fdcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='bs-navbar']/ul/li[2]/a</value>
      <webElementGuid>89b39b19-adbe-4782-b9eb-a467f278e95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Onboarding')]</value>
      <webElementGuid>afd0e6e4-0b70-4158-a3ba-ad6ca0c97c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>6b4619b9-76eb-4bcf-819d-a76e2eeea426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Positions'])[1]/preceding::a[1]</value>
      <webElementGuid>8506ab25-074c-4fc4-a02f-59c954f122f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calendar'])[1]/preceding::a[2]</value>
      <webElementGuid>0a158afa-70e5-4bea-a42f-26d476941cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Onboarding']/parent::*</value>
      <webElementGuid>614794f5-1096-4785-9a4c-793cf7f11b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>f49bbbf6-0e20-4d38-b41f-ddaed4f40218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>0ebcf7ae-588e-4acc-afc0-983b814cee92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Onboarding' or . = 'Onboarding')]</value>
      <webElementGuid>246060fd-71e3-4e3e-9139-bcc65767470d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
